package sn.ondmoney.txe.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.ondmoney.txe.domain.AssertUtils.bigDecimalCompareTo;

public class CashOutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashOutAllPropertiesEquals(CashOut expected, CashOut actual) {
        assertCashOutAutoGeneratedPropertiesEquals(expected, actual);
        assertCashOutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashOutAllUpdatablePropertiesEquals(CashOut expected, CashOut actual) {
        assertCashOutUpdatableFieldsEquals(expected, actual);
        assertCashOutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashOutAutoGeneratedPropertiesEquals(CashOut expected, CashOut actual) {
        assertThat(actual)
            .as("Verify CashOut auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashOutUpdatableFieldsEquals(CashOut expected, CashOut actual) {
        assertThat(actual)
            .as("Verify CashOut relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getSenderId()).as("check senderId").isEqualTo(expected.getSenderId()))
            .satisfies(a -> assertThat(a.getReceiverId()).as("check receiverId").isEqualTo(expected.getReceiverId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCashOutUpdatableRelationshipsEquals(CashOut expected, CashOut actual) {
        // empty method
    }
}
