package sn.ondmoney.txe.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.ondmoney.txe.domain.AssertUtils.bigDecimalCompareTo;

public class TransferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAllPropertiesEquals(Transfer expected, Transfer actual) {
        assertTransferAutoGeneratedPropertiesEquals(expected, actual);
        assertTransferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAllUpdatablePropertiesEquals(Transfer expected, Transfer actual) {
        assertTransferUpdatableFieldsEquals(expected, actual);
        assertTransferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAutoGeneratedPropertiesEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferUpdatableFieldsEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer relevant properties")
            .satisfies(a -> assertThat(a.getTxId()).as("check txId").isEqualTo(expected.getTxId()))
            .satisfies(a -> assertThat(a.getExternalTxId()).as("check externalTxId").isEqualTo(expected.getExternalTxId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getFees()).as("check fees").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFees()))
            .satisfies(a -> assertThat(a.getSenderPhone()).as("check senderPhone").isEqualTo(expected.getSenderPhone()))
            .satisfies(a -> assertThat(a.getReceiverPhone()).as("check receiverPhone").isEqualTo(expected.getReceiverPhone()))
            .satisfies(a -> assertThat(a.getInitiatedAt()).as("check initiatedAt").isEqualTo(expected.getInitiatedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getFailedAt()).as("check failedAt").isEqualTo(expected.getFailedAt()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferUpdatableRelationshipsEquals(Transfer expected, Transfer actual) {
        // empty method
    }
}
